-- AlterTable
ALTER TABLE "Stock" ADD COLUMN     "percentageChange" DOUBLE PRECISION,
ADD COLUMN     "realChange" DOUBLE PRECISION,
ADD COLUMN     "status" TEXT,
ADD COLUMN     "step" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
